### ISSUE TITLE
Single thread refactored fork

### ISSUE THREAD

**Issue by eduyayo** [dyanikoglu/FoolishFootballRevamp#4]
Hi,
I've refactored all the code in my fork https://github.com/eduyayo/FoolishFootballRevamp.git for it not to have all the overload of a thread-per-thing-stuff.

There's a single thread now running everything and runs smooth.

Could you review the thing and, maybe, merge?

**Comment by dyanikoglu** [comment]
Oh that's very interesting, I was not expecting someone to work on this project :)

The reason that I have used unnecessary threads were more about my school project which required involving threading in my work :)

I will review your code asap, and probably merge it, thanks for the contribution!

**Comment by dyanikoglu** [comment]
Can you also open a pull request?

**Comment by eduyayo** [comment]
done https://github.com/dyanikoglu/FoolishFootballRevamp/pull/5

**Comment by eduyayo** [comment]
Now... How Hard could it be... Separating business from presentation. Use an entity engine to keep easy adding functionality and ha e AI VS AI matches... 
Can u see those feasible?

Btw. The most importante one would be making this thing work with bigger time steps, Maybe even half a second.????
